# ------------------------------------------------------------
#  skript-weekly-end-reset（繁體中文版）
#  https://github.com/Im-Tim-mI/skript-weekly-end-reset
#  Copyright (c) 2026 廷廷小教室、廷廷的家（Tim945）
#  授權：MIT + Commons Clause（詳見 LICENSE）
# ------------------------------------------------------------

# 測試時間格式腳本
# 用完可刪除

command /testtime:
    permission: op
    trigger:
        set {_time} to now formatted as "HH:mm"
        set {_day} to now formatted as "EEEE"
        send "&e時間格式: &f%{_time}%"
        send "&e星期格式: &f%{_day}%"
